#!/bin/bash

#Script that uses zoxide query to auto start or attach to a tmux session

dir=$(zoxide query -i "$1")

# Check if zoxide found a directory
if [ -z "$dir" ]; then
  echo "No directory found for: $1"
  exit 1
fi

# Create a session name using the last folder name
session_name=$(basename "$dir")

# Use tmux to create or attach to the session
tmux new -As "$session_name" -c "$dir"
